package com.zx.demo.domain.mybatis;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    private String user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sex
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.age
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    private String age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.isExpired
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    private String isExpired;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.isEnabled
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    private String isEnabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.isLocked
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    private String isLocked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.isCredentialsExpired
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    private String isCredentialsExpired;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.rec_creator
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    private String rec_creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.rec_create_time
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    private String rec_create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.rec_revisor
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    private String rec_revisor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.rec_revisor_time
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    private String rec_revisor_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    public String getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param user_id the value for user.user_id
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sex
     *
     * @return the value of user.sex
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sex
     *
     * @param sex the value for user.sex
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.age
     *
     * @return the value of user.age
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.age
     *
     * @param age the value for user.age
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    public void setAge(String age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.isExpired
     *
     * @return the value of user.isExpired
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    public String getIsExpired() {
        return isExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.isExpired
     *
     * @param isExpired the value for user.isExpired
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    public void setIsExpired(String isExpired) {
        this.isExpired = isExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.isEnabled
     *
     * @return the value of user.isEnabled
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    public String getIsEnabled() {
        return isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.isEnabled
     *
     * @param isEnabled the value for user.isEnabled
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    public void setIsEnabled(String isEnabled) {
        this.isEnabled = isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.isLocked
     *
     * @return the value of user.isLocked
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    public String getIsLocked() {
        return isLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.isLocked
     *
     * @param isLocked the value for user.isLocked
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    public void setIsLocked(String isLocked) {
        this.isLocked = isLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.isCredentialsExpired
     *
     * @return the value of user.isCredentialsExpired
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    public String getIsCredentialsExpired() {
        return isCredentialsExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.isCredentialsExpired
     *
     * @param isCredentialsExpired the value for user.isCredentialsExpired
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    public void setIsCredentialsExpired(String isCredentialsExpired) {
        this.isCredentialsExpired = isCredentialsExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.rec_creator
     *
     * @return the value of user.rec_creator
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    public String getRec_creator() {
        return rec_creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.rec_creator
     *
     * @param rec_creator the value for user.rec_creator
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    public void setRec_creator(String rec_creator) {
        this.rec_creator = rec_creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.rec_create_time
     *
     * @return the value of user.rec_create_time
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    public String getRec_create_time() {
        return rec_create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.rec_create_time
     *
     * @param rec_create_time the value for user.rec_create_time
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    public void setRec_create_time(String rec_create_time) {
        this.rec_create_time = rec_create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.rec_revisor
     *
     * @return the value of user.rec_revisor
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    public String getRec_revisor() {
        return rec_revisor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.rec_revisor
     *
     * @param rec_revisor the value for user.rec_revisor
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    public void setRec_revisor(String rec_revisor) {
        this.rec_revisor = rec_revisor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.rec_revisor_time
     *
     * @return the value of user.rec_revisor_time
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    public String getRec_revisor_time() {
        return rec_revisor_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.rec_revisor_time
     *
     * @param rec_revisor_time the value for user.rec_revisor_time
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    public void setRec_revisor_time(String rec_revisor_time) {
        this.rec_revisor_time = rec_revisor_time;
    }
}