package com.zx.demo.dao.mybatis;

import com.zx.demo.domain.mybatis.AuthorityResource;
import com.zx.demo.domain.mybatis.AuthorityResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuthorityResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_resource
     *
     * @mbg.generated Sat Feb 24 14:39:01 CST 2018
     */
    long countByExample(AuthorityResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_resource
     *
     * @mbg.generated Sat Feb 24 14:39:01 CST 2018
     */
    int deleteByExample(AuthorityResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_resource
     *
     * @mbg.generated Sat Feb 24 14:39:01 CST 2018
     */
    int deleteByPrimaryKey(String authority_resource_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_resource
     *
     * @mbg.generated Sat Feb 24 14:39:01 CST 2018
     */
    int insert(AuthorityResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_resource
     *
     * @mbg.generated Sat Feb 24 14:39:01 CST 2018
     */
    int insertSelective(AuthorityResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_resource
     *
     * @mbg.generated Sat Feb 24 14:39:01 CST 2018
     */
    List<AuthorityResource> selectByExample(AuthorityResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_resource
     *
     * @mbg.generated Sat Feb 24 14:39:01 CST 2018
     */
    AuthorityResource selectByPrimaryKey(String authority_resource_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_resource
     *
     * @mbg.generated Sat Feb 24 14:39:01 CST 2018
     */
    int updateByExampleSelective(@Param("record") AuthorityResource record, @Param("example") AuthorityResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_resource
     *
     * @mbg.generated Sat Feb 24 14:39:01 CST 2018
     */
    int updateByExample(@Param("record") AuthorityResource record, @Param("example") AuthorityResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_resource
     *
     * @mbg.generated Sat Feb 24 14:39:01 CST 2018
     */
    int updateByPrimaryKeySelective(AuthorityResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_resource
     *
     * @mbg.generated Sat Feb 24 14:39:01 CST 2018
     */
    int updateByPrimaryKey(AuthorityResource record);
}