package com.zx.demo.dao.mybatis;

import com.zx.demo.domain.mybatis.AuthorityResource;

public interface AuthorityResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_resource
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    int deleteByPrimaryKey(String authority_resource_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_resource
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    int insert(AuthorityResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_resource
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    int insertSelective(AuthorityResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_resource
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    AuthorityResource selectByPrimaryKey(String authority_resource_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_resource
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    int updateByPrimaryKeySelective(AuthorityResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority_resource
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    int updateByPrimaryKey(AuthorityResource record);
}