package com.zx.demo.dao.mybatis;

import com.zx.demo.domain.mybatis.Resource;

public interface ResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    int deleteByPrimaryKey(String resource_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    int insert(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    int insertSelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    Resource selectByPrimaryKey(String resource_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    int updateByPrimaryKeySelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    int updateByPrimaryKey(Resource record);
}