package com.zx.demo.dao.mybatis;

import com.zx.demo.domain.mybatis.Role;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    int deleteByPrimaryKey(String role_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    Role selectByPrimaryKey(String role_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    int updateByPrimaryKey(Role record);
}