package com.zx.demo.dao.mybatis;

import com.zx.demo.domain.mybatis.RoleAuthority;

public interface RoleAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    int deleteByPrimaryKey(String role_authority_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    int insert(RoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    int insertSelective(RoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    RoleAuthority selectByPrimaryKey(String role_authority_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    int updateByPrimaryKeySelective(RoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority
     *
     * @mbg.generated Sat Apr 28 14:57:02 CST 2018
     */
    int updateByPrimaryKey(RoleAuthority record);
}