package com.zx.demo.dao.mybatis;

import com.zx.demo.domain.mybatis.RoleAuthority;
import com.zx.demo.domain.mybatis.RoleAuthorityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority
     *
     * @mbg.generated Sat Feb 24 14:39:01 CST 2018
     */
    long countByExample(RoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority
     *
     * @mbg.generated Sat Feb 24 14:39:01 CST 2018
     */
    int deleteByExample(RoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority
     *
     * @mbg.generated Sat Feb 24 14:39:01 CST 2018
     */
    int deleteByPrimaryKey(String role_authority_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority
     *
     * @mbg.generated Sat Feb 24 14:39:01 CST 2018
     */
    int insert(RoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority
     *
     * @mbg.generated Sat Feb 24 14:39:01 CST 2018
     */
    int insertSelective(RoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority
     *
     * @mbg.generated Sat Feb 24 14:39:01 CST 2018
     */
    List<RoleAuthority> selectByExample(RoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority
     *
     * @mbg.generated Sat Feb 24 14:39:01 CST 2018
     */
    RoleAuthority selectByPrimaryKey(String role_authority_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority
     *
     * @mbg.generated Sat Feb 24 14:39:01 CST 2018
     */
    int updateByExampleSelective(@Param("record") RoleAuthority record, @Param("example") RoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority
     *
     * @mbg.generated Sat Feb 24 14:39:01 CST 2018
     */
    int updateByExample(@Param("record") RoleAuthority record, @Param("example") RoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority
     *
     * @mbg.generated Sat Feb 24 14:39:01 CST 2018
     */
    int updateByPrimaryKeySelective(RoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority
     *
     * @mbg.generated Sat Feb 24 14:39:01 CST 2018
     */
    int updateByPrimaryKey(RoleAuthority record);
}